name: llm_autobahn_backend
channels:
  - defaults
dependencies:
  - annotated-doc=0.0.4
  - annotated-types=0.6.0
  - anyio=4.10.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - certifi=2026.01.04
  - click=8.2.1
  - dnspython=2.8.0
  - email-validator=2.3.0
  - exceptiongroup=1.3.0
  - fastapi=0.128.0
  - fastapi-cli=0.0.20
  - fastapi-core=0.128.0
  - h11=0.16.0
  - httpcore=1.0.9
  - httptools=0.7.1
  - httpx=0.28.1
  - idna=3.11
  - jinja2=3.1.6
  - libffi=3.4.4
  - libuv=1.48.0
  - libzlib=1.3.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - mdurl=0.1.2
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pydantic-extra-types=2.11.0
  - pydantic-settings=2.12.0
  - pygments=2.19.2
  - pyjwt=2.10.1
  - python=3.10.13
  - python-dotenv=1.1.0
  - python-multipart=0.0.20
  - pyyaml=6.0.3
  - readline=8.3
  - rich=14.2.0
  - rich-toolkit=0.17.1
  - setuptools=80.9.0
  - shellingham=1.5.4
  - sniffio=1.3.1
  - sqlite=3.51.1
  - starlette=0.47.3
  - tk=8.6.15
  - tomli=2.4.0
  - typer=0.20.0
  - typer-slim=0.20.0
  - typer-slim-standard=0.20.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - uvicorn=0.40.0
  - uvicorn-standard=0.40.0
  - uvloop=0.22.1
  - watchfiles=1.1.1
  - websockets=15.0.1
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
